export const profession = [
	"Agriculture",
	"Architecture",
	"Banking",
	"Biotech",
	"Engineering",
	"Science",
	"Construction",
	"Education",
	"Entertainment",
	"Fashion",
	"Finance",
	"F&B",
	"Healthcare",
	"Hospitality",
	"IT",
	"Insurance",
	"Law",
	"Manufacturing",
	"Marketing",
	"Media",
	"Mining",
	"Invesments",
	"Retail",
	"Travel",
	"Other",
];
export const position = ["Employee", "Leader", "Monitoring", "Manager", "Director", "Intern", "Other"];

export const salary = [
	"5 ~ 10 mil / month",
	"10 ~ 20 mil / month",
	"Above 20 mil / month",
	"Above 35 mil / month",
	"Negotiate",
];
export const form = ["FullTime", "PartTime", "Remote", "Freelance", "Contract", "Temporary", "Other"];
export const location = [
	"An Giang",
	"Ba Ria - Vung Tau",
	"Bac Giang",
	"Bac Kan",
	"Bac Lieu",
	"Bac Ninh",
	"Ben Tre",
	"Binh Dinh",
	"Binh Duong",
	"Binh Phuoc",
	"Binh Thuan",
	"Ca Mau",
	"Can Tho",
	"Cao Bang",
	"Da Nang",
	"Dak Lak",
	"Dak Nong",
	"Dien Bien",
	"Dong Nai",
	"Dong Thap",
	"Gia Lai",
	"Ha Giang",
	"Ha Nam",
	"Ha Noi",
	"Ha Tinh",
	"Hai Duong",
	"Hai Phong",
	"Hau Giang",
	"Hoa Binh",
	"Hung Yen",
	"Khanh Hoa",
	"Kien Giang",
	"Kon Tum",
	"Lai Chau",
	"Lam Dong",
	"Lang Son",
	"Lao Cai",
	"Long An",
	"Nam Dinh",
	"Nghe An",
	"Ninh Binh",
	"Ninh Thuan",
	"Phu Tho",
	"Phu Yen",
	"Quang Binh",
	"Quang Nam",
	"Quang Ngai",
	"Quang Ninh",
	"Quang Tri",
	"Soc Trang",
	"Son La",
	"Tay Ninh",
	"Thai Binh",
	"Thai Nguyen",
	"Thanh Hoa",
	"Thua Thien Hue",
	"Tien Giang",
	"Ho Chi Minh",
	"Tra Vinh",
	"Tuyen Quang",
	"Vinh Long",
	"Vinh Phuc",
	"Yen Bai",
];

export const exp = ["None", "Above 6 Month", "1 ~ 2 Year", "2 ~ 3 Year", "3 ~ 5 Year", "Other"];
